### ISSUE TITLE
You should use abstractions provided by Spring JPA Repository

### ISSUE THREAD

**Issue by ondrej-smola** [Tmthetom/ppj_project#4]
@Query("SELECT row FROM Comment_Rating AS row WHERE row.id_comment = :id_comment")
    public List<Comment_Rating> getCommentRatings(@Param("id_comment") int id_comment);

Simple queries like this should be written without using custom/own queries

**Comment by Tmthetom** [comment]
Simplification will be implemented soon as possible (today night, or upcoming days).

**Comment by Tmthetom** [comment]
Simplification done only in few cases (get specific object by ID).

In other cases (M:N tables), like example you provided at start of this issue (above), i didnt find way, how to get List of objects, when they have IdClass (M:N table) and i want only one part of composite key to fit match. If i want one specific CommentRatingId, i can use getPersistenceUnitUtil from EntityManagerFactory, but in this case, i dont know how to do it directly from Service. Would be glad if you give me some hint.

**Comment by ondrej-smola** [comment]
http://docs.spring.io/spring-data/jpa/docs/1.9.6.RELEASE/reference/html/#repositories.query-methods.query-creation

should be something like 

`List<CommentRating> findByCommentId(int commentId) `

**Comment by Tmthetom** [comment]
Fixed all cases. Thank you for help.
